version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bankerize
    container_name: bankerize
    restart: unless-stopped
    working_dir: /var/www
    #command: bash -c "php artisan migrate"
    environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=bankerize
            - DB_USERNAME=root
            - DB_PASSWORD=root
    volumes:
      - .:/var/www
    ports:
          - '8000:8000'
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bankerize
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
